cd ..\src
copy BaseObjects\BaseObjects.h .
copy BaseObjects\ManuProcEntity.h .
copy BaseObjects\ManuProcVorgang.h .
copy BaseObjects\MVC.h .
copy BaseObjects\Model.h .
copy BaseObjects\ModelPlex.h .
copy BaseObjects\Model_ref_bvector.h .
copy BaseObjects\RadioModel.h .
copy BaseObjects\SignalPlex.h .
copy Misc\Ausgabe_neu.h .
copy Misc\CacheStatic.h .
copy Misc\Cache_Pointer.h .
copy Misc\Date.h .
copy Misc\Datum.h .
copy Misc\EmptyInt_4TeX.h .
copy Misc\EntryValueBase.h .
copy Misc\EntryValueDatum.h .
copy Misc\EntryValueEmptyInt.h .
copy Misc\EntryValueFixed.h .
copy Misc\EntryValueFixedEinheit.h .
copy Misc\EntryValueIntGermanString.h .
copy Misc\EntryValueIntString.h .
copy Misc\EntryValueInvert.h .
copy Misc\EntryValueSort.h .
copy Misc\EntryValueTimeStamp.h .
copy Misc\Event.h .
copy Misc\ExtraColumns.h .
copy Misc\FILEstream.h .
copy Misc\FetchIStream.h .
copy Misc\Global_Settings.h .
copy Misc\Handles.h .
copy Misc\IOerror.h .
copy Misc\Interval.h .
copy Misc\Kalenderwoche.h .
copy Misc\libManuProc_Base_dll.h .
copy Misc\Long.h .
copy Misc\Pointer.h .
copy Misc\Postgres.h .
copy Misc\Query.h .
copy Misc\Rundungsmacros.h .
copy Misc\SQLerror.h .
copy Misc\SQLerror_postgres.h .
copy Misc\SQLerror_sqlite.h .
copy Misc\Tag.h .
copy Misc\TagStream.h .
copy Misc\TemporaryValue.h .
copy Misc\TimeStamp.h .
copy Misc\Trace.h .
copy Misc\TraceNV.h .
copy Misc\Transaction.h .
copy Misc\UniqueValue.h .
copy Misc\Zeitpunkt_new.h .
copy Misc\algorithm.h .
copy Misc\auto_init.h .
copy Misc\bitmask.h .
copy Misc\c++ostream.h .
copy Misc\callbackbuf.h .
copy Misc\compiler_ports.h .
copy Misc\create_parse.h .
copy Misc\ctime_assert.h .
copy Misc\dbconnect.h .
copy Misc\exception.h .
copy Misc\fixedpoint.h .
copy Misc\germanstring.h .
copy Misc\i18n.h .
copy Misc\inbetween.h .
copy Misc\intmap.h .
copy Misc\itos.h .
copy Misc\mystream.h .
copy Misc\mystring.h .
copy Misc\pg_type.h .
copy Misc\recodestream.h .
copy Misc\relops.h .
copy Misc\safemap.h .
copy Misc\string0.h .
copy Misc\vectormap.h .
