cd ..\src
md BaseObjects
copy ManuProcEintrag.h BaseObjects
copy ManuProcEntity.h BaseObjects
copy ManuProcVorgang.h BaseObjects
copy MVC.h BaseObjects
copy Model.h BaseObjects
copy ModelPlex.h BaseObjects
copy Model_ref_bvector.h BaseObjects
copy RadioModel.h BaseObjects
md Misc
copy Ausgabe_neu.h Misc
copy CacheStatic.h Misc
copy Cache_Pointer.h Misc
copy Date.h Misc
copy Datum.h Misc
copy EmptyInt_4TeX.h Misc
copy EntryValueBase.h Misc
copy EntryValueDatum.h Misc
copy EntryValueEmptyInt.h Misc
copy EntryValueFixed.h Misc
copy EntryValueFixedEinheit.h Misc
copy EntryValueIntGermanString.h Misc
copy EntryValueIntString.h Misc
copy EntryValueInvert.h Misc
copy EntryValueSort.h Misc
copy EntryValueTimeStamp.h Misc
copy Event.h Misc
copy ExtraColumns.h Misc
copy FILEstream.h Misc
copy FetchIStream.h Misc
copy Global_Settings.h Misc
copy Handles.h Misc
copy IOerror.h Misc
copy Interval.h Misc
copy Kalenderwoche.h Misc
copy libManuProc_Base_dll.h Misc
copy Long.h Misc
copy Pointer.h Misc
copy Postgres.h Misc
copy Query.h Misc
copy Rundungsmacros.h Misc
copy SQLerror.h Misc
copy SQLerror_postgres.h Misc
copy SQLerror_sqlite.h Misc
copy SignalPlex.h Misc
copy Tag.h Misc
copy TagStream.h Misc
copy TemporaryValue.h Misc
copy TimeStamp.h Misc
copy Trace.h Misc
copy TraceNV.h Misc
copy Transaction.h Misc
copy UniqueValue.h Misc
copy Zeitpunkt_new.h Misc
copy algorithm.h Misc
copy auto_init.h Misc
copy bitmask.h Misc
copy c++ostream.h Misc
copy callbackbuf.h Misc
copy compiler_ports.h Misc
copy create_parse.h Misc
copy ctime_assert.h Misc
copy dbconnect.h Misc
copy exception.h Misc
copy fixedpoint.h Misc
copy germanstring.h Misc
copy i18n.h Misc
copy inbetween.h Misc
copy intmap.h Misc
copy itos.h Misc 
copy mystream.h Misc
copy mystring.h Misc
copy pg_type.h Misc
copy recodestream.h Misc
copy relops.h Misc
copy safemap.h Misc
copy string0.h Misc
copy vectormap.h Misc
