#! /bin/bash

PLATFORM=$1

mkdir -p ../../runtime_ManuProC_Base/$PLATFORM

cp .libs/libManuProC_Base.a ../../runtime_ManuProC_Base/$PLATFORM

CHG=`git diff HEAD --name-only | wc -l`
if [ $CHG -ne 0 ]
then
  echo "not tracked" > ../../runtime_ManuProC_Base/stampfile
else
  echo `git rev-parse HEAD` > ../../runtime_ManuProC_Base/stampfile
fi
    




